version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    restart: always # Will restart if there is any failure
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
        # For win machines, use the below volume path.
      # - elasticsearch-data:/usr/share/elasticsearch/data
        # For macOS, create the below path in your dir, and give propper access.
        - elasticsearch-data:/Users/johnmartinez/Desktop/docker-volumes/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch # Creates a dependency on the elasticsearch docker in case of restarting
volumes:
  elasticsearch-data:
    driver: local # Means is going to store the volume local in the PC.

# Running cmd: docker-compose -f elasticsearch-kibana.yml up -d
