apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: dev
        - name: POSTGRES_PASSWORD
          value: dev
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: postgres-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres-deployment
  minReplicas: 1
  maxReplicas: 5  # You can adjust this value as needed
  targetCPUUtilizationPercentage: 50  # Adjust based on your application's resource requirements
