apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: ZGV2  # base64 encoded 'dev'
  MONGO_INITDB_ROOT_PASSWORD: ZGV2  # base64 encoded 'dev'

